#+BEGIN_EXPORT markdown
---
layout: post
title: Literate Emacs Config
category: fun
tags: 
keywords: emacs
description: Sharing my literate emacs config
importance: 1
img: assets/img/Emacs.png
date: 2023-05-22
---
#+end_export

#+title: .emacs.d
#+author: Johnny Sigman
#+OPTIONS: toc:nil

* About

This web page is a tangled version of my literate [[https://github.com/jsigman/emacs-config][elisp config]]. Throughout this document, you may find helpful notes, tricks, and comments. I have been tinkering with emacs in some way since 2013. I made this repeatable and git-controlled in 2019, and in 2023 I began to publish it on my web site.

** Notes on code blocks
If a code block is active, then it will appear with ~emacs-lisp~ syntax highlighting. If it's not being used, then it will show up with ~plaintext~ highlighting. For example:

#+BEGIN_EXPORT markdown
{% highlight plaintext %}
(print "This code will not be run!")
{% endhighlight %}
#+END_EXPORT

#+BEGIN_EXPORT markdown
{% highlight emacs-lisp %}
(print "This code is run in my config!")
{% endhighlight %}
#+END_EXPORT

Whether a code block is run at load time is controlled by the ~:load yes~ block argument of ~literate-elisp~.

* ~init.el~
This is the main init file that wraps all the other code
I love and rely heavily on ~straight.el~.
#+BEGIN_EXPORT markdown
{% highlight emacs-lisp %}
#+END_EXPORT
#+include: "init.el" :minlevel 1
#+BEGIN_EXPORT markdown
{% endhighlight %}
#+END_EXPORT

* Package Management
I love and rely heavily on ~straight.el~.
#+BEGIN_EXPORT markdown
{% highlight emacs-lisp %}
#+END_EXPORT
#+include: "packages-settings.el" :minlevel 1
#+BEGIN_EXPORT markdown
{% endhighlight %}
#+END_EXPORT

#+include: "init.org" :minlevel 1
