name: publish
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "workflows"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "publish"
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # print hello world
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup emacs
        run: |
          sudo apt-get update
          sudo apt-get install emacs tree
          emacs --version
      - name: Publish to markdown
        run: |
          emacs --batch --load .github/publish.el
      - name: Commit
        run: |
          git config --global user.name 'Workflow'
          git config --global user.email ''
          git add published_version.md
          git commit -m 'Update published version'
          git push
      - name: Close
        run: exit 0
