name: knit
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "workflows"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "publish"
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # print hello world
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print publish.el file
        run: cat .github/publish.el
      - name: Close
        run: exit 0

      # - name: setup
      #   run: |
      #     pwd
      #     ls -l
      #     sudo apt-get update
      #     sudo apt-get install emacs tree
      #     tree
      #     emacs --batch --load .github/publish.el
