name: knit
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "workflows"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # print hello world
      - name: setup
        run: |
          pwd
          ls -l
          cd ..
          ls -l
          pwd
          sudo apt-get update
          sudo apt-get install emacs tree
          tree
          emacs --batch --load .github/publish.el
