name: test-load-emacs

on:
  push:
    branches:
      - develop-ci-flow
      - main
  pull_request: {}

env:
  EMACS_DIR: ${{ github.workspace }}/.emacs.d

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: .emacs.d
      - name: Configure Emacs
        run: |
          sudo apt-add-repository ppa:ubuntu-elisp/ppa
          sudo apt-get update
          sudo apt-get install emacs-snapshot
          emacs --version

      - name: Initialize Emacs
        run: |
          emacs --batch -L ${{ env.EMACS_DIR }} --eval "(progn (toggle-debug-on-error)(load \"${{ env.EMACS_DIR }}/early-init.el\" nil t)(load (concat user-emacs-directory \"init.el\") nil t)(setq initial-buffer-choice t))"
          echo "Emacs initialized successfully!"
      - name: Verify Initialization
        run: |
          if [ $? -eq 0 ]; then
            echo "Emacs initialized successfully!"
          else
            echo "Emacs failed to initialize."
            exit 1
          fi
